# Generated by Django 3.2.2 on 2021-07-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countsession',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now=True)),
                ('population', models.IntegerField()),
                ('num_not_sortable', models.IntegerField()),
            ],
            options={
                'db_table': 'countsession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lifeform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('deformed', models.BooleanField()),
                ('length_max', models.IntegerField()),
                ('length_min', models.IntegerField()),
                ('length_avg', models.IntegerField()),
                ('length_std', models.IntegerField()),
            ],
            options={
                'db_table': 'lifeform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizeWeightData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'size_weight_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizeWeightModels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'size_weight_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
