# Generated by Django 3.2.2 on 2021-06-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'countsession',
            },
        ),
        migrations.CreateModel(
            name='size_weight_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'size_weight_model',
            },
        ),
        migrations.CreateModel(
            name='tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tank',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='size_weight_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('size', models.IntegerField()),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeweightdatatocountsession', to='datavisualisation.countsession')),
            ],
            options={
                'db_table': 'size_weight_data',
            },
        ),
        migrations.CreateModel(
            name='lifeform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('length_max', models.IntegerField()),
                ('length_min', models.IntegerField()),
                ('length_avg', models.IntegerField()),
                ('length_std', models.IntegerField()),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifeformtocountsession', to='datavisualisation.countsession')),
            ],
            options={
                'db_table': 'lifeform',
            },
        ),
        migrations.AddField(
            model_name='countsession',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countsessiontouser', to='datavisualisation.user'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='size_weight_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countsessiontosizeweightmodel', to='datavisualisation.size_weight_model'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='tank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countsessiontotank', to='datavisualisation.tank'),
        ),
    ]
