# Generated by Django 3.2.2 on 2021-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualisation', '0002_auto_20210610_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeWeightData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'size_weight_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizeWeightModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'size_weight_model',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='size_weight_data',
            name='session_id',
        ),
        migrations.DeleteModel(
            name='size_weight_model',
        ),
        migrations.DeleteModel(
            name='size_weight_data',
        ),
    ]
